---
title: "GAISEing at a lecture hall: effective pedagogy in large-enrollment courses."
author: |
  | Matthew D. Beckman
  | Penn State University
date: ""
output: pdf_document
---

# Abstract: 
There is a rich body of research in Statistics Education studying efficient pedagogy, particularly in the introductory statistics curriculum, but much of this work has occurred in the context of smaller class sizes.  At many institutions, introductory statistics course(s) frequently occur in a large-enrollment face-to-face setting where recommended pedagogy (beyond perhaps clickers & think-pair-share) can seem daunting.  The 2016 update to the ASA endorsed Guidelines for Assessment and Instruction in Statistics Education (GAISE) College Report now includes expanded coverage of this subject.  This roundtable will discuss experiences with implementation of the 2016 GAISE recommendations in large-enrollment face-to-face courses, share successes and challenges, and explore additional strategies to improve teaching, learning, and engagement in large-enrollment classes.  Such topics may include integration of active learning, student use of technology, and student engagement \emph{during} "lecture" periods as well as ideas for achieving balance between a rich project experience and a sensible grading load.

